name: 'Deploy Environment'
inputs:
  env_name:
    required: true
  port:
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout app code
      uses: actions/checkout@v4
      with:
        repository: mtararujs/python-greetings
        path: app-${{ inputs.env_name }}
    
    - name: Stop existing service
      shell: powershell
      run: pm2 delete greetings-app-${{ inputs.env_name }} ; $global:LASTEXITCODE = 0
    
    - name: Start service with PM2
      shell: powershell
      working-directory: ./app-${{ inputs.env_name }}
      run: |
        echo "Deploying to ${{ inputs.env_name }} on port ${{ inputs.port }}"
        cmd /c "pm2 start app.py --name greetings-app-${{ inputs.env_name }} --interpreter ${{ github.workspace }}\python-app\venv\Scripts\python.exe -- --port ${{ inputs.port }}"